# Generated by Django 4.2.5 on 2023-09-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("user_id", models.IntegerField()),
                ("True", models.DateField(verbose_name="False")),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Interactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive", models.BooleanField()),
                ("user_id", models.IntegerField()),
                ("True", models.DateField(verbose_name="False")),
                (
                    "comment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.comments"
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.posts"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comments",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.posts"
            ),
        ),
        migrations.AddField(
            model_name="comments",
            name="response_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.comments"
            ),
        ),
    ]
